### ISSUE TITLE
implement header

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/realmate#1]
Create a header with the following menu:

create header component in src/components
desgin: https://www.figma.com/file/zwLA88lKxJl5Hg8R3eDCDb/Untitled?type=design&node-id=0%3A1&mode=design&t=L2zbFLHS786DhlS0-1

**Comment by rajanarahul93** [comment]
"Designed and implemented header component with Home, Project, Heros, Blog, and GitHub repository link icons based on the provided Figma design." PLEASE ASSIGN ME THIS #1

**Comment by rajanarahul93** [comment]
Got it, thanks!

**Comment by devvsakib** [comment]
Hi @rajanarahul93 , any update?
