### ISSUE TITLE
[FEAT]: make header mobile responsive

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/realmate#10]
**Is your feature request related to a problem? Please describe.**
make header mobile responsive

![image](https://github.com/devvsakib/realmate/assets/88339569/96a57822-c18b-4e08-a42c-4b46aa18aefa)

**Comment by du1ana** [comment]
Hi, I like to work on this feature. Please assign it to me.

**Comment by du1ana** [comment]
@devvsakib could you assign me to this issue? 😊
