### ISSUE TITLE
create testimonial slider with swiperjs

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/realmate#14]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/devvsakib/realmate/assets/88339569/d07294c5-eb39-474b-8d82-ce0fcbb3e730)

design this awesome testimonial slider using swiperjs.

Figma: https://www.figma.com/file/zwLA88lKxJl5Hg8R3eDCDb/hacktoberfest?type=design&node-id=0-1&mode=design&t=A9bXhrDtmyGr8ROY-0

**Comment by ikunal-04** [comment]
Hey @devvsakib can I work on this issue?

**Comment by NegativE333** [comment]
Hey, I like to work on this issue.

**Comment by Abhii-07** [comment]
@devvsakib Hey, I am new to open source and would be grateful if you give this opportunity to me. Thanks!

**Comment by NegativE333** [comment]
Hi @devvsakib ,

I hope you're doing well. I noticed that you've assigned this issue to me, and I wanted to check in on the status of my pull request. I've created a pull request for this issue, which you can find in the pull requests.

Have you had a chance to review it? I'm eager to hear your feedback and suggestions. I'm open to making any adjustments if needed, so please feel free to share your thoughts.

Thank you for your time and consideration.

**Comment by devvsakib** [comment]
> Hi @devvsakib ,
> 
> I hope you're doing well. I noticed that you've assigned this issue to me, and I wanted to check in on the status of my pull request. I've created a pull request for this issue, which you can find in the pull requests.
> 
> Have you had a chance to review it? I'm eager to hear your feedback and suggestions. I'm open to making any adjustments if needed, so please feel free to share your thoughts.
> 
> Thank you for your time and consideration.

will review when I'm free. ASAP
