### ISSUE TITLE
implement footer

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/realmate#2]
Create a footer with the following requirements:

There should be at least 3 columns with a logo and a 1/2 line description under the logo, a menu on the right side, and a link to the GitHub repository with icon. and design as you want. make sure to make it look better, you can use svg shape too, most welcome.

You can install react-icons.(highly recommended)

desgin: https://www.figma.com/file/zwLA88lKxJl5Hg8R3eDCDb/Untitled?type=design&node-id=0%3A1&mode=design&t=L2zbFLHS786DhlS0-1

**Comment by rajanarahul93** [comment]
"Implemented a custom footer with 3 columns, logo and descriptions, a menu, and a GitHub repository link, enhancing the design for better aesthetics and user experience." "Please assign the issue to me for resolution."

**Comment by CoderRedwing** [comment]
please assign me

**Comment by CoderRedwing** [comment]
implement footer #2  I am fixed this bug kindly accept the pr
