### ISSUE TITLE
[MEDIUM]: create login page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/realmate#23]
**Is your feature request related to a problem? Please describe.**
Create a login page and get hacktoberfest accepted label

**Describe the solution you'd like**
![image](https://github.com/devvsakib/realmate/assets/88339569/6c701f7e-9a89-4b5a-98c9-7df223c15afa)

As close as possible, use tailwind, all color added, if not added, you can add from Figma.

- create a file in the pages folder called singin.js
- make sure to use components for form and other common design
- use react-icons for icon
- use tailwind
- No functionality needed for validation, only design

Find design here
FIgma: https://www.figma.com/file/zwLA88lKxJl5Hg8R3eDCDb/hacktoberfest?type=design&node-id=0%3A1&mode=design&t=eNqzoLkTKfEbikim-1

**Comment by Abhishek-Sood** [comment]
i d like to contribute please assign it to me

**Comment by Abhishek-Sood** [comment]
;) if anythings not upto the mark please tell so ....and add the hacktoberfest-accepted label
